#!/usr/bin/env ruby
#
# Module workflow tool, used mostly during development
#
module_name = 'sshkeys'
module_dir = '/var/lib/puppet/modules/'

task :default  => :test do
   puts "rsync -axm --exclude=Rakefile * #{module_dir}#{module_name}"
   sh "rsync -axm * #{module_dir}#{module_name}"
end

task :dirs do
  puts "Creating Local Directory Setup"
  sh "mkdir -p manifests templates files"
end

task :test do 
   puts "puppet --noop --parseonly manifests/init.pp"
   sh   "puppet --noop --parseonly manifests/init.pp"
   puts "All OK"
end
