#!/usr/bin/env ruby
#
# Module workflow tool, used mostly during development
#
module_name = Dir.pwd.split('/')[-1]
if module_name == "common"
  puts "Don't rake in the common directory."
  exit 1
end
module_dir = '/var/lib/puppet/modules/'
dirs = [ 'manifests', 'files', 'templates' , 'depends', 'test' ] 

"The Default Task"
task :default  => :test do
   puts "rsync -axm --exclude=Rakefile * #{module_dir}#{module_name}"
   sh "rsync -axm * #{module_dir}#{module_name}"
end

task :dirs do
  puts "Creating Local Directory Setup"
  d = dirs.join(' ')
  sh "mkdir -p #{d} ; touch manifests/init.pp"
end

task :validate do
   sh   "puppet --noop --parseonly manifests/init.pp"
end

task :test => :validate do 
   sh   "puppet --modulepath=. --modulepath=#{module_dir}  test/test.pp"
end

task :clean do
   dirs = [ 'manifests', 'files', 'templates' , 'depends', 'test' ] 
   dirs.each do |d| 
     if File.exists?(d) and Dir["#{d}/*"].empty?
       Dir.rmdir(d)
     end
   end
end
