#!/usr/bin/env ruby
#
# Module workflow tool, used mostly during development
#
#
#
task :default  => :test do

  
   puts "mkdir -p /var/lib/puppet/modules/daap_server/manifests"
   sh   "mkdir -p /var/lib/puppet/modules/daap_server/manifests"
   puts "install -p -m644 manifests/* /var/lib/puppet/modules/daap_server/manifests"
   sh   "install -p -m644 manifests/* /var/lib/puppet/modules/daap_server/manifests"
#   puts "install -p -m644 manifests/* /var/lib/puppet/modules/daap_server/files"
#   sh   "install -p -m644 manifests/* /var/lib/puppet/modules/daap_server/files"
   puts "install -p -m644 manifests/* /var/lib/puppet/modules/daap_server/templates"
   sh   "install -p -m644 manifests/* /var/lib/puppet/modules/daap_server/templates"

end

task :test do 
   puts "puppet --noop --parseonly manifests/init.pp"
   sh   "puppet --noop --parseonly manifests/init.pp"
   puts "All OK"
end

